"""initial schema

Revision ID: d24918ffed14
Revises: 
Create Date: 2025-12-21 16:45:07.457300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd24918ffed14'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approved_idea_submissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('approved_idea', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_approved_idea_phone_date', 'approved_idea_submissions', ['phone', 'created_at'], unique=False)
    op.create_index(op.f('ix_approved_idea_submissions_created_at'), 'approved_idea_submissions', ['created_at'], unique=False)
    op.create_index(op.f('ix_approved_idea_submissions_phone'), 'approved_idea_submissions', ['phone'], unique=False)
    op.create_table('idea_submissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('interests', sa.Text(), nullable=False),
    sa.Column('generated_idea', sa.Text(), nullable=False),
    sa.Column('generation_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_idea_phone', 'idea_submissions', ['phone', 'created_at'], unique=False)
    op.create_index('idx_idea_user', 'idea_submissions', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_idea_submissions_created_at'), 'idea_submissions', ['created_at'], unique=False)
    op.create_index(op.f('ix_idea_submissions_user_id'), 'idea_submissions', ['user_id'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('features', sa.Text(), nullable=False),
    sa.Column('blog_included', sa.Boolean(), nullable=True),
    sa.Column('max_projects', sa.Integer(), nullable=True),
    sa.Column('support_level', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('is_addon', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('signup_step', sa.String(), nullable=True),
    sa.Column('selected_plan_id', sa.String(), nullable=True),
    sa.Column('has_synopsis', sa.Boolean(), nullable=True),
    sa.Column('needs_idea_generation', sa.Boolean(), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_created', 'users', ['created_at'], unique=False)
    op.create_index('idx_user_email_admin', 'users', ['email', 'is_admin'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_admin'), 'users', ['is_admin'], unique=False)
    op.create_table('activity_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_activity_entity', 'activity_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_activity_status_action', 'activity_logs', ['status', 'action'], unique=False)
    op.create_index('idx_activity_user_action_date', 'activity_logs', ['user_id', 'action', 'created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_action'), 'activity_logs', ['action'], unique=False)
    op.create_index(op.f('ix_activity_logs_created_at'), 'activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_table('admin_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('request_type', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('admin_response', sa.Text(), nullable=True),
    sa.Column('admin_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_requests_user_id'), 'admin_requests', ['user_id'], unique=False)
    op.create_table('meetings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('meeting_date', sa.DateTime(), nullable=True),
    sa.Column('meeting_link', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_user_id'), 'meetings', ['user_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=True),
    sa.Column('plan_name', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('service_type', sa.String(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('payment_proof_path', sa.String(), nullable=True),
    sa.Column('payment_proof_original_name', sa.String(), nullable=True),
    sa.Column('payment_proof_uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('payment_verified_at', sa.DateTime(), nullable=True),
    sa.Column('payment_verified_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['payment_verified_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_order_plan_status', 'orders', ['plan_id', 'status'], unique=False)
    op.create_index('idx_order_user_status', 'orders', ['user_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_plan_id'), 'orders', ['plan_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('tech_stack', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('idea_generated', sa.Boolean(), nullable=True),
    sa.Column('synopsis_submitted', sa.Boolean(), nullable=True),
    sa.Column('synopsis_file_path', sa.String(), nullable=True),
    sa.Column('synopsis_original_name', sa.String(), nullable=True),
    sa.Column('project_file_path', sa.String(), nullable=True),
    sa.Column('project_file_original_name', sa.String(), nullable=True),
    sa.Column('project_url', sa.String(), nullable=True),
    sa.Column('url_approved', sa.Boolean(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_project_category_status', 'projects', ['category', 'status'], unique=False)
    op.create_index('idx_project_user_status', 'projects', ['user_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_projects_category'), 'projects', ['category'], unique=False)
    op.create_index(op.f('ix_projects_created_at'), 'projects', ['created_at'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('synopsis',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('original_name', sa.String(), nullable=False),
    sa.Column('file_size', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_synopsis_status_date', 'synopsis', ['status', 'created_at'], unique=False)
    op.create_index('idx_synopsis_user_status', 'synopsis', ['user_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_synopsis_created_at'), 'synopsis', ['created_at'], unique=False)
    op.create_index(op.f('ix_synopsis_status'), 'synopsis', ['status'], unique=False)
    op.create_index(op.f('ix_synopsis_user_id'), 'synopsis', ['user_id'], unique=False)
    op.create_table('user_services',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('service_id', sa.String(), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chatbot_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('message_type', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('context', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('intent', sa.String(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chatbot_intent', 'chatbot_history', ['intent', 'created_at'], unique=False)
    op.create_index('idx_chatbot_project', 'chatbot_history', ['project_id'], unique=False)
    op.create_index('idx_chatbot_user_session', 'chatbot_history', ['user_id', 'session_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_chatbot_history_created_at'), 'chatbot_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_chatbot_history_session_id'), 'chatbot_history', ['session_id'], unique=False)
    op.create_index(op.f('ix_chatbot_history_user_id'), 'chatbot_history', ['user_id'], unique=False)
    op.create_table('idea_generation_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('tech_stack', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('features', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('complexity', sa.String(), nullable=True),
    sa.Column('estimated_duration', sa.String(), nullable=True),
    sa.Column('user_selected', sa.Boolean(), nullable=True),
    sa.Column('user_rating', sa.String(), nullable=True),
    sa.Column('refinement_count', sa.String(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('prompt_used', sa.Text(), nullable=True),
    sa.Column('generation_model', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_idea_category', 'idea_generation_history', ['category', 'user_selected'], unique=False)
    op.create_index('idx_idea_project', 'idea_generation_history', ['project_id'], unique=False)
    op.create_index('idx_idea_user_selected', 'idea_generation_history', ['user_id', 'user_selected', 'created_at'], unique=False)
    op.create_index(op.f('ix_idea_generation_history_category'), 'idea_generation_history', ['category'], unique=False)
    op.create_index(op.f('ix_idea_generation_history_created_at'), 'idea_generation_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_idea_generation_history_user_id'), 'idea_generation_history', ['user_id'], unique=False)
    op.create_index(op.f('ix_idea_generation_history_user_selected'), 'idea_generation_history', ['user_selected'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_idea_generation_history_user_selected'), table_name='idea_generation_history')
    op.drop_index(op.f('ix_idea_generation_history_user_id'), table_name='idea_generation_history')
    op.drop_index(op.f('ix_idea_generation_history_created_at'), table_name='idea_generation_history')
    op.drop_index(op.f('ix_idea_generation_history_category'), table_name='idea_generation_history')
    op.drop_index('idx_idea_user_selected', table_name='idea_generation_history')
    op.drop_index('idx_idea_project', table_name='idea_generation_history')
    op.drop_index('idx_idea_category', table_name='idea_generation_history')
    op.drop_table('idea_generation_history')
    op.drop_index(op.f('ix_chatbot_history_user_id'), table_name='chatbot_history')
    op.drop_index(op.f('ix_chatbot_history_session_id'), table_name='chatbot_history')
    op.drop_index(op.f('ix_chatbot_history_created_at'), table_name='chatbot_history')
    op.drop_index('idx_chatbot_user_session', table_name='chatbot_history')
    op.drop_index('idx_chatbot_project', table_name='chatbot_history')
    op.drop_index('idx_chatbot_intent', table_name='chatbot_history')
    op.drop_table('chatbot_history')
    op.drop_table('user_services')
    op.drop_index(op.f('ix_synopsis_user_id'), table_name='synopsis')
    op.drop_index(op.f('ix_synopsis_status'), table_name='synopsis')
    op.drop_index(op.f('ix_synopsis_created_at'), table_name='synopsis')
    op.drop_index('idx_synopsis_user_status', table_name='synopsis')
    op.drop_index('idx_synopsis_status_date', table_name='synopsis')
    op.drop_table('synopsis')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_created_at'), table_name='projects')
    op.drop_index(op.f('ix_projects_category'), table_name='projects')
    op.drop_index('idx_project_user_status', table_name='projects')
    op.drop_index('idx_project_category_status', table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_plan_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_index('idx_order_user_status', table_name='orders')
    op.drop_index('idx_order_plan_status', table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_meetings_user_id'), table_name='meetings')
    op.drop_table('meetings')
    op.drop_index(op.f('ix_admin_requests_user_id'), table_name='admin_requests')
    op.drop_table('admin_requests')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_created_at'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_action'), table_name='activity_logs')
    op.drop_index('idx_activity_user_action_date', table_name='activity_logs')
    op.drop_index('idx_activity_status_action', table_name='activity_logs')
    op.drop_index('idx_activity_entity', table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_users_is_admin'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index('idx_user_email_admin', table_name='users')
    op.drop_index('idx_user_created', table_name='users')
    op.drop_table('users')
    op.drop_table('services')
    op.drop_table('plans')
    op.drop_index(op.f('ix_idea_submissions_user_id'), table_name='idea_submissions')
    op.drop_index(op.f('ix_idea_submissions_created_at'), table_name='idea_submissions')
    op.drop_index('idx_idea_user', table_name='idea_submissions')
    op.drop_index('idx_idea_phone', table_name='idea_submissions')
    op.drop_table('idea_submissions')
    op.drop_index(op.f('ix_approved_idea_submissions_phone'), table_name='approved_idea_submissions')
    op.drop_index(op.f('ix_approved_idea_submissions_created_at'), table_name='approved_idea_submissions')
    op.drop_index('idx_approved_idea_phone_date', table_name='approved_idea_submissions')
    op.drop_table('approved_idea_submissions')
    # ### end Alembic commands ###
